---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: emqx-pdb
  namespace: iot-edge
  labels:
    app: emqx
spec:
  minAvailable: 1  # At least 1 pod must be available during updates/evictions
  selector:
    matchLabels:
      app: emqx
